env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - prettier
  - standard
  - eslint:recommended
  - plugin:jest/recommended
plugins:
  - 'prettier'
  - 'jest'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  parser: 'babel-eslint'
  allowImportExportEverywhere: true
rules:
  {
    strict: 0,
    prettier/prettier: 2,
    no-console: 1,
    eqeqeq: 2,
    no-eq-null: 1,
    no-multi-spaces: 1,
    no-useless-escape: 0,
    camelcase: 1,
    semi: ["error", "always"],
    comma-dangle: 0,
    space-before-function-paren: 0,
    max-len: ['error', { code: 135, ignoreComments: true, ignoreUrls: true }],
    indent: 0,
    curly: [0, 'multi'],
    jest/no-done-callback: 0,
    import/no-duplicates: 0,
    jest/no-test-prefixes: 0,
    jest/no-disabled-tests: 0,
  }
